### ISSUE TITLE
Filter by device class?

### ISSUE THREAD

**Issue by poldim** [custom-cards/monster-card#12]
Following up on [this previous issue](https://github.com/ciotlosm/custom-lovelace/issues/199), I can't get this filter working.

```
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: All doors
        filter:
          include:
            - attributes:
              device_class: door
```

The card does show in the UI but it shows (maybe) all of my entities in HA (cameras, device trackers, covers, etc).

So, how should this be configured to only show the `door` device class?
