### ISSUE TITLE
Cannot apply card-mod styles

### ISSUE THREAD

**Issue by tomlut** [custom-cards/monster-card#4]
Using [card-mod](https://github.com/thomasloven/lovelace-card-mod) this border style works for every type of card I've tried except the monster card:
```
card:
  title: Lights On
  type: entities
filter:
  exclude:
    - entity_id: '*light.all_*'
    - entity_id: '*light.lifx.kitchen_*'
    - entity_id: '*light.lifx.lounge_*'
    - entity_id: '*light.lifx.cinema_*'
    - entity_id: '*light.lifx.bar_*'
    - entity_id: '*light.lifx_mstr_bed_*'
  include:
    - domain: light
      state: 'on'
show_empty: false
type: 'custom:monster-card'
style: | ### <-------------------  does not apply
  ha-card {
    border: solid 2px var(--primary-color);
  }
```
I also tried:
```
style: |
  ha-card {
    border: solid 2px var(--primary-color) !important;
  }
```
No luck.

Is it possible to rectify this?
