### ISSUE TITLE
State comparison doesn't work with negative value

### ISSUE THREAD

**Issue by Spirituss** [custom-cards/monster-card#6]
In case one needs to compare entity state with negative value the component shows nothing.
Example of the yaml:
```
  - type: custom:monster-card 
    card:
      type: entities
      title: Weak Wi-Fi
    filter:
      include:
        - entity_id: "*status_*"
          state: '< -80'
```
