### ISSUE TITLE
Attributes with a space

### ISSUE THREAD

**Issue by gregg098** [custom-cards/monster-card#7]
I recently installed Zigbee2MQTT and some of my sensors don't show actual battery level anywhere, but do have an attribute "battery low" with true or false. When I try to add this to the monster card, I cannot get any state of "battery low" to show up. I've tried a million variations of quotes, *'s, etc. on both the attribute name and state and I cannot get it to show any entities, true or false.  I believe that the space is throwing it off. Is there a workaround?

Here is the card config. It works for everything except that particular attribute case.

```
card:
  show_header_toggle: false
  title: Low Battery Devices
  type: entities
filter:
  include:
    - entity_id: '*battery_level*'
      state: < 25
    - attributes:
        battery_level: < 25
    - attributes:
        battery: < 25
    - attributes:
        battery low: 'true'
show_empty: false
type: 'custom:monster-card'
```

![image](https://user-images.githubusercontent.com/24879443/62162962-3ee96100-b2ce-11e9-9c28-00d65e24cfa1.png)
