### ISSUE TITLE
attribute filtering not working with sonos_group

### ISSUE THREAD

**Issue by skylartaylor** [custom-cards/monster-card#8]
Hi, I am trying to filter based on whether a sonos speaker is grouped or on its own, and I have the following YAML as my monster-card:
```  
- type: 'custom:monster-card'
    show_empty: false
    filter:
      include:
        - entity_id: media_player.kitchen
          attributes:
            sonos_group: media_player.kitchen
    card:
      - type: 'custom:mini-media-player'
        entity: media_player.kitchen
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.great_room
              name: Great Room
            - entity_id: media_player.kitchen
              name: Kitchen
            - entity_id: media_player.bedroom
              name: Bedroom
```
But the filter is not working - the card never shows. I am able to filter on other attributes that return `true` or `false`. I have also tried wrapping the attribute as a strong, or object, none of which make a difference.

Any help would be appreciated!
