### ISSUE TITLE
media-control is not a valid type

### ISSUE THREAD

**Issue by foxsam21** [custom-cards/monster-card#9]
If I try to configure media players like this:
```
  - title: 'Music Players'
    path: music_players
    cards:
      - type: custom:monster-card
        show_empty: false
        card:
          title: 'Players'
          type: media-control
        filter:
          include:
          - entity_id: "media_player.*"
```
I get nothing. It works if I change the line `type: media-control` to `type: entities` but I don't get a media control where I can click to play or skip etc... I get an entity.
It seems like the `type: media-control` is broken.

**Comment by airdrummingfool** [comment]
Possibly relatedly, The card type `custom:mini-media-player` ([Mini Media Player](https://github.com/kalkih/mini-media-player)) is also not working.

**Comment by airdrummingfool** [comment]
After looking into this a bit, it appears that monster-card only supports Lovelace cards that accept multiple entities; cards like `media-control`, `custom:mini-media-player`, `entity-button`, etc only accept one.

The issue is that monster-card calls `setConfig()` with a config object that has the entities in `config.entities`, while the single-entity cards' `setConfig()` methods expect a single entity in  `config.entity`.
![image](https://user-images.githubusercontent.com/631249/63409068-0eb94d80-c3b6-11e9-8aab-25fc7253c93d.png)

**Comment by iantrich** [comment]
correct. checkout https://github.com/thomasloven/lovelace-auto-entities

**Comment by airdrummingfool** [comment]
Awesome, thanks! It was a bit tricky to get working, so here's a sample `auto-entities` card for anyone else looking for this functionality:

Note that `card`>`type` **must** be `entities`, and the single-entity card type (e.g. `media-control`) is set in `filter`>`include/exclude`>`options`>`type`.

```yaml
type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - domain: media_player
      state: playing
      options:
        type: 'custom:mini-media-player'
```
